apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "4"
              memory: "64Gi"
            limits:
              cpu: "4"
              memory: "64Gi"
          volumeMounts:
            - name: data-volume
              mountPath: /mnt/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
